<?xml version="1.0" encoding="utf-8"?><Database Name="Roster" Class="RosterDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=Roster;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RosterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Team" Member="Teams">
    <Type Name="Team">
      <Column Name="TeamId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Wins" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Losses" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ties" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Score" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Team_Player" Member="Players" ThisKey="TeamId" OtherKey="TeamId" Type="Player" />
    </Type>
  </Table>
  <Table Name="dbo.Player" Member="Players">
    <Type Name="Player">
      <Column Name="PlayerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TeamId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BNetTag" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SkillRating" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AverageKills" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="AverageDeaths" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="AverageAssists" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Team_Player" Member="Team" ThisKey="TeamId" OtherKey="TeamId" Type="Team" IsForeignKey="true" />
    </Type>
  </Table>
</Database>